import {
  DiJavascript1,
  DiMongodb,
  DiNpm,
  DiGit,
  DiVisualstudio,
  DiReact,
} from 'react-icons/di';
import { SiTypescript } from 'react-icons/si';
import { IoLogoNodejs } from 'react-icons/io';
import { SiVite } from 'react-icons/si';

export const icons = [
  DiMongodb,
  DiJavascript1,
  DiGit,
  DiNpm,
  DiVisualstudio,
  DiReact,
  IoLogoNodejs,
  SiTypescript,
  SiVite,
  DiMongodb,
  DiJavascript1,
  DiGit,
  DiNpm,
  DiVisualstudio,
  DiReact,
  IoLogoNodejs,
  SiTypescript,
  SiVite,
  DiMongodb,
  DiJavascript1,
  DiGit,
  DiNpm,
  DiVisualstudio,
  DiReact,
  IoLogoNodejs,
  SiTypescript,
  SiVite,
  DiMongodb,
  DiJavascript1,
  DiGit,
  DiNpm,
  DiVisualstudio,
  DiReact,
  IoLogoNodejs,
  SiTypescript,
  SiVite,
  DiMongodb,
  DiJavascript1,
  DiGit,
  DiNpm,
  DiVisualstudio,
  DiReact,
  IoLogoNodejs,
  SiTypescript,
  SiVite,
  DiMongodb,
  DiJavascript1,
  DiGit,
  DiNpm,
  DiVisualstudio,
  DiReact,
  IoLogoNodejs,
  SiTypescript,
  SiVite,
  DiMongodb,
  DiJavascript1,
  DiGit,
  DiNpm,
  DiVisualstudio,
  DiReact,
  IoLogoNodejs,
  SiTypescript,
  SiVite,
];
